[root at 2024-04-12 17:51:12,084]: Archipelago (0.4.5) logging initialized on Windows-10-10.0.22631-SP0 running Python 3.11.3
[Client at 2024-04-12 17:51:12,090]: Connecting to Archipelago server at ws://192.168.0.210:38281
[Client at 2024-04-12 17:51:12,101]: Connected
[Client at 2024-04-12 17:51:12,101]: --------------------------------
[Client at 2024-04-12 17:51:12,101]: Room Information:
[Client at 2024-04-12 17:51:12,101]: --------------------------------
[Client at 2024-04-12 17:51:12,101]: Server protocol version: 0.4.5, generator version: 0.4.5, tags: AP
[Client at 2024-04-12 17:51:12,102]: Release permission: auto
[Client at 2024-04-12 17:51:12,102]: Remaining permission: goal
[Client at 2024-04-12 17:51:12,102]: Collect permission: auto
[Client at 2024-04-12 17:51:12,102]: A !hint costs 10% of your total location count as points and you get 1 for each location checked. Use !hint for more information.
[Client at 2024-04-12 17:51:12,103]: Lost connection to the multiworld server, type /connect to reconnect
Traceback (most recent call last):
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\CommonClient.py", line 664, in server_loop
    await process_server_cmd(ctx, msg)
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\CommonClient.py", line 762, in process_server_cmd
    ctx.event_invalid_slot()
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\CommonClient.py", line 337, in event_invalid_slot
    raise Exception('Invalid Slot; please verify that you have connected to the correct world.')
Exception: Invalid Slot; please verify that you have connected to the correct world.
