[root at 2024-04-15 23:05:27,453]: Archipelago (0.4.5) logging initialized on Windows-10-10.0.22631-SP0 running Python 3.11.3
[Client at 2024-04-15 23:05:27,467]: Connecting to Archipelago server at ws://192.168.0.210:38281
[Client at 2024-04-15 23:05:27,487]: Connected
[Client at 2024-04-15 23:05:27,488]: --------------------------------
[Client at 2024-04-15 23:05:27,488]: Room Information:
[Client at 2024-04-15 23:05:27,488]: --------------------------------
[Client at 2024-04-15 23:05:27,489]: Server protocol version: 0.4.5, generator version: 0.4.5, tags: AP
[Client at 2024-04-15 23:05:27,489]: Release permission: auto
[Client at 2024-04-15 23:05:27,489]: Remaining permission: goal
[Client at 2024-04-15 23:05:27,489]: Collect permission: auto
[Client at 2024-04-15 23:05:27,489]: A !hint costs 10% of your total location count as points and you get 1 for each location checked. Use !hint for more information.
[FileLog at 2024-04-15 23:05:27,491]: EthanSotReal (Team #1) playing Sea of Thieves has joined. Client(1.1.1), [].
[FileLog at 2024-04-15 23:05:27,492]: Now that you are connected, you can use !help to list commands to run via the server. If your client supports it, you may have additional local commands you can list with /help.
[Client at 2024-04-15 23:06:20,035]: Lost connection to the multiworld server, type /connect to reconnect
Traceback (most recent call last):
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\venv\Lib\site-packages\websockets\legacy\protocol.py", line 963, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\venv\Lib\site-packages\websockets\legacy\protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\venv\Lib\site-packages\websockets\legacy\protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\venv\Lib\site-packages\websockets\legacy\protocol.py", line 1165, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\venv\Lib\site-packages\websockets\legacy\framing.py", line 98, in read
    data = await reader(length)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\asyncio\streams.py", line 718, in readexactly
    raise self._exception
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 305, in _loop_reading
    self._read_fut = self._loop._proactor.recv_into(self._sock, self._data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 486, in recv_into
    ov.WSARecvInto(conn.fileno(), buf, flags)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\CommonClient.py", line 662, in server_loop
    async for data in ctx.server.socket:
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\venv\Lib\site-packages\websockets\legacy\protocol.py", line 498, in __aiter__
    yield await self.recv()
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\venv\Lib\site-packages\websockets\legacy\protocol.py", line 568, in recv
    await self.ensure_open()
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\venv\Lib\site-packages\websockets\legacy\protocol.py", line 939, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
[root at 2024-04-15 23:07:54,189]: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\Utils.py", line 551, in queuer
    text = stream.readline().strip()
           ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_stdin.py", line 117, in readline
    result = self.original_stdin.readline(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
