[root at 2024-04-15 22:56:45,714]: Archipelago (0.4.5) logging initialized on Windows-10-10.0.22631-SP0 running Python 3.11.3
[Client at 2024-04-15 22:56:45,729]: Connecting to Archipelago server at ws://192.168.0.210:38281
[Client at 2024-04-15 22:56:50,637]: Connected
[Client at 2024-04-15 22:56:50,638]: --------------------------------
[Client at 2024-04-15 22:56:50,639]: Room Information:
[Client at 2024-04-15 22:56:50,639]: --------------------------------
[Client at 2024-04-15 22:56:50,639]: Server protocol version: 0.4.5, generator version: 0.4.5, tags: AP
[Client at 2024-04-15 22:56:50,639]: Release permission: auto
[Client at 2024-04-15 22:56:50,639]: Remaining permission: goal
[Client at 2024-04-15 22:56:50,639]: Collect permission: auto
[Client at 2024-04-15 22:56:50,639]: A !hint costs 10% of your total location count as points and you get 1 for each location checked. Use !hint for more information.
[Client at 2024-04-15 22:56:50,640]: Lost connection to the multiworld server, type /connect to reconnect
Traceback (most recent call last):
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\CommonClient.py", line 664, in server_loop
    await process_server_cmd(ctx, msg)
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\CommonClient.py", line 762, in process_server_cmd
    ctx.event_invalid_slot()
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\CommonClient.py", line 337, in event_invalid_slot
    raise Exception('Invalid Slot; please verify that you have connected to the correct world.')
Exception: Invalid Slot; please verify that you have connected to the correct world.
[root at 2024-04-15 22:57:36,572]: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "C:\Users\Ethan\Desktop\code\Archipelago-main\Archipelago-main\Utils.py", line 551, in queuer
    text = stream.readline().strip()
           ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_stdin.py", line 117, in readline
    result = self.original_stdin.readline(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
